# from app.schema import BaseResponse
from schema import BaseResponse #test

class ResponseConstant:
    SUCCESS = BaseResponse(responseCode="00", responseMessage="Completed successfully")
    REFER_TO_CARD_ISSUER = BaseResponse(responseCode="01", responseMessage="Refer to card issuer")
    REFER_TO_CARD_ISSUERS_SPECIAL_CONDITIONS = BaseResponse(responseCode="02", responseMessage="Refer to card issuer's special conditions")
    INVALID_MERCHANT = BaseResponse(responseCode="03", responseMessage="Invalid merchant")
    PICK_UP = BaseResponse(responseCode="04", responseMessage="Pick-up")
    DO_NOT_HONOR = BaseResponse(responseCode="05", responseMessage="Do not honor")
    PICK_UP_CARD_SPECIAL_CONDITION = BaseResponse(responseCode="07", responseMessage="Pick-up card, special condition")
    HONOUR_WITH_IDENTIFICATION = BaseResponse(responseCode="08", responseMessage="Honour with identification")
    REQUEST_IN_PROGRESS = BaseResponse(responseCode="09", responseMessage="Request in progress")
    APPROVED_FOR_PARTIAL_AMOUNT = BaseResponse(responseCode="10", responseMessage="Approved for partial amount")
    APPROVED_VIP = BaseResponse(responseCode="11", responseMessage="Approved (VIP)")
    INVALID_TRANSACTION = BaseResponse(responseCode="12", responseMessage="Invalid transaction")
    INVALID_AMOUNT = BaseResponse(responseCode="13", responseMessage="Invalid amount")
    INVALID_CARD_NUMBER_NO_SUCH_NUMBER = BaseResponse(responseCode="14", responseMessage="Invalid card number (no such number)")
    NO_SUCH_ISSUER = BaseResponse(responseCode="15", responseMessage="No such issuer")
    APPROVED_UPDATE_TRACK_3 = BaseResponse(responseCode="16", responseMessage="Approved, update track 3")
    CUSTOMER_CANCELLATION = BaseResponse(responseCode="17", responseMessage="Customer cancellation")
    CUSTOMER_DISPUTE = BaseResponse(responseCode="18", responseMessage="Customer dispute")
    RE_ENTER_TRANSACTION = BaseResponse(responseCode="19", responseMessage="Re-enter transaction")
    INVALID_RESPONSE = BaseResponse(responseCode="20", responseMessage="Invalid response")
    NO_ACTION_TAKEN = BaseResponse(responseCode="21", responseMessage="No action taken")
    SUSPECTED_MALFUNCTION = BaseResponse(responseCode="22", responseMessage="Something Went Wrong")
    UNACCEPTABLE_TRANSACTION_FEE = BaseResponse(responseCode="23", responseMessage="Unacceptable transaction fee")
    FILE_UPDATE_NOT_SUPPORTED_BY_RECEIVER = BaseResponse(responseCode="24", responseMessage="File update not supported by receiver")
    UNABLE_TO_LOCATE_RECORD = BaseResponse(responseCode="25", responseMessage="Unable to locate record")
    DUPLICATE_RECORD = BaseResponse(responseCode="26", responseMessage="Duplicate record")
    FILE_UPDATE_FIELD_EDIT_ERROR = BaseResponse(responseCode="27", responseMessage="File update field edit error")
    FILE_UPDATE_FILE_LOCKED_OUT = BaseResponse(responseCode="28", responseMessage="File update file locked out")
    FILE_UPDATE_NOT_SUCCESSFUL_CONTACT_ACQUIRER = BaseResponse(responseCode="29", responseMessage="File update not successful, contact acquirer")
    FORMAT_ERROR = BaseResponse(responseCode="30", responseMessage="Format error")
    BANK_NOT_SUPPORTED_BY_SWITCH = BaseResponse(responseCode="31", responseMessage="Bank not supported by switch")
    COMPLETED_PARTIALLY = BaseResponse(responseCode="32", responseMessage="Completed partially")
    EXPIRED_CARD = BaseResponse(responseCode="33", responseMessage="Expired card")
    SUSPECTED_FRAUD = BaseResponse(responseCode="34", responseMessage="Suspected fraud")
    CARD_ACCEPTOR_CONTACT_ACQUIRER = BaseResponse(responseCode="35", responseMessage="Card acceptor contact acquirer")
    RESTRICTED_CARD = BaseResponse(responseCode="36", responseMessage="Restricted card")
    CARD_ACCEPTOR_CALL_ACQUIRER_SECURITY = BaseResponse(responseCode="37", responseMessage="Card acceptor call acquirer security")
    ALLOWABLE_PIN_TRIES_EXCEEDED = BaseResponse(responseCode="38", responseMessage="Allowable PIN tries exceeded")
    NO_CREDIT_ACCOUNT = BaseResponse(responseCode="39", responseMessage="No credit account")
    REQUESTED_FUNCTION_NOT_SUPPORTED = BaseResponse(responseCode="40", responseMessage="Requested function not supported")
    LOST_CARD = BaseResponse(responseCode="41", responseMessage="Lost card")
    NO_UNIVERSAL_ACCOUNT = BaseResponse(responseCode="42", responseMessage="No universal account")
    STOLEN_CARD_PICK_UP = BaseResponse(responseCode="43", responseMessage="Stolen card, pick-up")
    NO_INVESTMENT_ACCOUNT = BaseResponse(responseCode="44", responseMessage="No investment account")
    NOT_SUFFICIENT_FUNDS = BaseResponse(responseCode="51", responseMessage="Not sufficient funds")
    NO_CHECKING_ACCOUNT = BaseResponse(responseCode="52", responseMessage="No checking account")
    NO_SAVINGS_ACCOUNT = BaseResponse(responseCode="53", responseMessage="No savings account")
    INCORRECT_PERSONAL_IDENTIFICATION_NUMBER = BaseResponse(responseCode="55", responseMessage="Incorrect personal identification number")
    NO_CARD_RECORD = BaseResponse(responseCode="56", responseMessage="No card record")
    TRANSACTION_NOT_PERMITTED_TO_CARDHOLDER = BaseResponse(responseCode="57", responseMessage="Transaction not permitted to cardholder")
    TRANSACTION_NOT_PERMITTED_TO_TERMINAL = BaseResponse(responseCode="58", responseMessage="Transaction not permitted to terminal")
    EXCEEDS_WITHDRAWAL_AMOUNT_LIMIT = BaseResponse(responseCode="61", responseMessage="Exceeds withdrawal amount limit")
    SECURITY_VIOLATION = BaseResponse(responseCode="63", responseMessage="Security violation")
    ORIGINAL_AMOUNT_INCORRECT = BaseResponse(responseCode="64", responseMessage="Original amount incorrect")
    EXCEEDS_WITHDRAWAL_FREQUENCY_LIMIT = BaseResponse(responseCode="65", responseMessage="Exceeds withdrawal frequency limit")
    CARD_ACCEPTOR_CALL_ACQUIRERS_SECURITY_DEPARTMENT = BaseResponse(responseCode="66", responseMessage="Card acceptor call acquirer's security department")
    HARD_CAPTURE_REQUIRES_THAT_CARD_BE_PICKED_UP_AT_ATM = BaseResponse(responseCode="67", responseMessage="Hard capture (requires that card be picked up at ATM)")
    RESPONSE_RECEIVED_TOO_LATE = BaseResponse(responseCode="68", responseMessage="Response received too late")
    ALLOWABLE_NUMBER_OF_PIN_TRIES_EXCEEDED = BaseResponse(responseCode="75", responseMessage="Allowable number of PIN tries exceeded")
    INVALID_CREDIT_ACCOUNT = BaseResponse(responseCode="76", responseMessage="Invalid Credit Account")
    INVALID_DEBIT_ACCOUNT = BaseResponse(responseCode="77", responseMessage="Invalid Debit Account")
    INVALID_ACCOUNT = BaseResponse(responseCode="78", responseMessage="Invalid Account")
    INVALID_ENTRY = BaseResponse(responseCode="79", responseMessage="Invalid Entry")
    AUTHORIZATION_KEY_MUST_BE_PASSED = BaseResponse(responseCode="80", responseMessage="Authorization Key must be passed")
    INVALID_ACTION = BaseResponse(responseCode="81", responseMessage="Invalid Action")
    ACCOUNT_DELETED = BaseResponse(responseCode="82", responseMessage="Your account has been deleted or suspended")
    ERROR_INVALID_DATE_FORMAT = BaseResponse(responseCode="83", responseMessage="Invalid date Format")
    ERROR_INVALID_PATH = BaseResponse(responseCode="84", responseMessage="Invalid Path")
    FAILED_TO_PERFORM_ACTION = BaseResponse(responseCode="85", responseMessage="Failed to perform action")
    ERROR_INVALID_CREDENTIAL = BaseResponse(responseCode="86", responseMessage="Invalid Credential")
    ERROR_ACTIVITY_ALREADY_QUEUED = BaseResponse(responseCode="87", responseMessage="Activity Already Queued Authorized")
    ERROR_ACTIVITY_ALREADY_PERFORMED = BaseResponse(responseCode="87", responseMessage="Activity Already Performed")
    SUCCESS_ACTIVITY_QUEUE = BaseResponse(responseCode="00", responseMessage="Activity Queued Awaiting Authorization")
    FAILED_TO_CREATE_RECORD = BaseResponse(responseCode="88", responseMessage="d")
    FAILED_TO_UPDATE_RECORD = BaseResponse(responseCode="89", responseMessage="Failed to update record")
    CUTOFF_IS_IN_PROCESS = BaseResponse(responseCode="90", responseMessage="Cutoff is in process")
    TRANSACTION_CAN_BE_SENT_AGAIN_IN_A_FEW_MINUTES = BaseResponse(responseCode="", responseMessage="(switch ending a day's business and starting the next. Transaction can be sent again in a few minutes)")
    ISSUER_OR_SWITCH_IS_INOPERATIVE = BaseResponse(responseCode="91", responseMessage="Issuer or switch is inoperative")
    FINANCIAL_INSTITUTION_OR_INTERMEDIATE_NETWORK_FACILITY_CANNOT_BE_FOUND_FOR_ROUTING = BaseResponse(responseCode="92", responseMessage="Financial institution or intermediate network facility cannot be found for routing")
    TRANSACTION_CANNOT_BE_COMPLETED_VIOLATION_OF_LAW = BaseResponse(responseCode="93", responseMessage="Transaction cannot be completed. Violation of law")
    DUPLICATE_TRANSMISSION = BaseResponse(responseCode="94", responseMessage="Duplicate transmission")
    RECONCILE_ERROR = BaseResponse(responseCode="95", responseMessage="Reconcile error")
    SYSTEM_MALFUNCTION = BaseResponse(responseCode="22", responseMessage="System malfunction")
    SUCCESS_UPLOAD_SUBMITTED = BaseResponse(responseCode="97", responseMessage="Failed to upload records.")
    ERROR_NO_PENDING_ENTRIES = BaseResponse(responseCode="98", responseMessage="No Pending Entries.")
    ERROR_INVALID_BANK_CODE = BaseResponse(responseCode="99", responseMessage="Invalid Bank Code")
    ERROR_AUTHENTICATION_FAILED = BaseResponse(responseCode="100", responseMessage="Authentication Failed")
    ERROR_FAILED_TO_GENERATE_OTP = BaseResponse(responseCode="101", responseMessage="Failed to generate OTP")
    ERROR_INVALID_TYPE = BaseResponse(responseCode="102", responseMessage="Invalid Type")
    ERROR_INVALID_INTEREST_RATE = BaseResponse(responseCode="103", responseMessage="Invalid interest Rate")
    ERROR_INVALID_CHECKER_ID = BaseResponse(responseCode="104", responseMessage="Invalid Checker ID")
    ERROR_PROCESSING = BaseResponse(responseCode="105", responseMessage="Processing Failed")
    LOW_CONFIDENCE = BaseResponse(responseCode="106", responseMessage="Low Confidence")